name: PowerShell on Target Machines

on:
  push:
    branches:
      - main  

jobs:
  powershell-task:
    uses: kirandevops1993/powershell-reusable/.github/workflows/reusable.yml@main
    with:
      Machines: ${{ 52.188.82.61 }}  # Use GitHub Secrets for sensitive data
      UserName: ${{ kiran }}
      UserPassword: ${{Extender#123 }}
      ScriptType: Inline  # Default value; update as needed
      ScriptPath: ""  # Required if ScriptType = FilePath
      InlineScript: ${{  InlineScriptContent }}  # Required if ScriptType = Inline
      ScriptArguments: ""  # Optional
      Sensitive_Alphanumeric_Info_1: ""  # Optional
      SessionVariables: ""  # Optional
      Sensitive_Alphanumeric_Info_2: Https  # Default value
      Sensitive_Alphanumeric_Info_3: Default  # Default value
      Sensitive_Alphanumeric_Info_4: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block'  # Default value
