name: PowerShell on Target Machines

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  powershell-task:
    uses: kiranvattikuti146/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main
    with:
      Machines: " 10.0.0.6"
      UserName: "azureuser"
      UserPassword: 'Extender#1234'
      ScriptType: "Inline"
      ScriptPath: ""
      InlineScript: |
        $hostname = hostname
        Write-Output "Executing on Host: $hostname"
        New-Item -Path 'C:\UsersazureuserDesktopfrom_10_5.txt' -ItemType File
      ScriptArguments: ""
      SessionVariables: ""
