name: PowerShell on Target Machines

on:
  push:
    branches:
      - main  

jobs:
  powershell-task:
    uses: kirandevops1993/powershell-reusable/.github/workflows/reusable.yml@main
    with:
      Machines:  52.188.82.61   
      UserName: TFS-2019\kiran
      UserPassword: Extender#123 
      ScriptType: Inline  # Default value; 
      ScriptPath: ""  # Required if ScriptType = FilePath
      InlineScript: ${{  InlineScriptContent }}  # Required if ScriptType = Inline
      ScriptArguments: ""  
      Sensitive_Alphanumeric_Info_1: ""  
      SessionVariables: ""  
      Sensitive_Alphanumeric_Info_2: Https  
      Sensitive_Alphanumeric_Info_3: Default  
      Sensitive_Alphanumeric_Info_4: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block'  # Default value
