name: PowerShell on Target Machines

on:
  push:
    branches:
      - main  

jobs:
  powershell-task:
    uses: ./reusable-workflows/powershell-task.yml
    with:
      Machines: ${{ secrets.Machines }}  # Use GitHub Secrets for sensitive data
      UserName: ${{ secrets.UserName }}
      UserPassword: ${{ secrets.UserPassword }}
      ScriptType: Inline  # Default value; update as needed
      ScriptPath: ""  # Required if ScriptType = FilePath
      InlineScript: ${{ secrets.InlineScript }}  # Required if ScriptType = Inline
      ScriptArguments: ""  # Optional
      Sensitive_Alphanumeric_Info_1: ""  # Optional
      SessionVariables: ""  # Optional
      Sensitive_Alphanumeric_Info_2: Https  # Default value
      Sensitive_Alphanumeric_Info_3: Default  # Default value
      Sensitive_Alphanumeric_Info_4: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block'  # Default value
